### ISSUE TITLE
I want view last 15 pages created

### ISSUE THREAD

**Issue by LeDistordu** [cosmocode/changes#30]
Code :

{{changes>type=create&count=15&maxage=31536000&render=pagelist(user, notags)}}

It's ok but pages eventually disappear before reaching 15

**Comment by Aleksey-Maksimov** [comment]
Hello.
A similar problem. 
Pages for a period more than **config:recent_days** not displayed

**Comment by LeDistordu** [comment]
No problem with modified page, just created page for me. I think there is an explanation because of dokuwiki working.

**Comment by Klap-in** [comment]
@Aleksey-Maksimov points the cause of this. 
Recent changes for the whole wiki are stored in `/data/meta/_dokuwiki.changes` and `/data/meta/_media.changes`. But this more a kind of global cache for a limited number of days. The limit is set by https://www.dokuwiki.org/config:recent_days

Per page also a changelog is maintained which are not influenced by this recent_days config. This is the listing of revisions you can see via the 'Old revisions' of a wiki page.

This Changes Plugin depends on the global changelog. If this changelog is truncated after `recent_days` than it will not show changes after this date. Solution is just increasing the `recent_days` config setting.

**Comment by bamboo122** [comment]
Is it possible to display more than just the one very recent change for a page? If I change something, the prevoius change disappears. I want to keep them all.
Thanks in advance!
