### ISSUE TITLE
User filter: allow exclusion of user(s)

### ISSUE THREAD

**Issue by shallimus** [cosmocode/changes#40]
Could the user argument be enhanced to allow exclusion of specific user(s)? The ns argument already does this.

My use case is a wiki where one user (me!) is currently making ~90% of the contributions, although other contributors are increasing their input as time goes by; several users have commented that it would be useful to see who else is making changes, since the large number of 

I imagine others might find this useful too; consider a wiki where a bot is making edits - might be nice to be able to exclude those, for instance.

The ns argument allows exclusion of specific namespaces; from the [documentation](https://www.dokuwiki.org/plugin:changes):

> The ns parameter supports both inclusion and exclusion of the namespaces. If a namespace name starts with a minus sign that namespace will be excluded. Also you can assign a number of namespaces as a comma separated list:
> 
> {{changes>ns = -foo}}
> {{changes>ns = foo, bar, -bar:ba

I'm not sure if there are any potential issues where a username might start with a -, but anecdotally I don't recall ever seeing a username which started with a -.

**Comment by shallimus** [comment]
Whoops - I didn't spot that there's already [a pull request for user exclusion](https://github.com/cosmocode/changes/pull/27) until after I posted this issue.

Could this be considered for inclusion in the plugin? I will test, and report back my results.

**Comment by shallimus** [comment]
Tested the pull request, with mixed results.

I replaced my syntax.php with the syntax.php in the pull request, and created a new instance of the change plugin:

`{{changes>type=all&userexclude=my.username&render=pagelist(noheader,showdiff)&count=100&}}`

While userexclude does then provide a list of all changes not by my.username, all instances of the Change plugin no longer provide username, which is a showstopper. I'll see if I can figure out why that's now broken.

**Comment by shallimus** [comment]
I revisited this. While I was unable to get the pull request I mention above working as I had hoped, I have managed to get my own version working. I started with the stock syntax.php from the 2016-01-24 version of the Changes plugin, and made these edits:
```
124a125,129
>             case 'excludedusers':
>                 foreach(preg_split('/\s*,\s*/', $value) as $value) {
>                     $data[$name][] = $value;
>                 }
>                 break;
163c168
<             $changes = $this->getChanges($data['count'], $data['ns'], $data['excludedpages'], $data['type'], $data['user'], $data['maxage']);
---
>             $changes = $this->getChanges($data['count'], $data['ns'], $data['excludedpages'], $data['type'], $data['user'], $data['maxage'], $data['excludedusers']);
196c201
<     protected function getChanges($num, $ns, $excludedpages, $type, $user, $maxage) {
---
>     protected function getChanges($num, $ns, $excludedpages, $type, $user, $maxage, $excludedusers) {
216c221
<             $change = $this->handleChangelogLine($lines[$i], $ns, $excludedpages, $type, $user, $maxage, $seen);
---
>             $change = $this->handleChangelogLine($lines[$i], $ns, $excludedpages, $type, $user, $maxage, $seen, $excludedusers);
248c253
<     protected function handleChangelogLine($line, $ns, $excludedpages, $type, $user, $maxage, &$seen) {
---
>     protected function handleChangelogLine($line, $ns, $excludedpages, $type, $user, $maxage, &$seen, $excludedusers) {
288a294,300
>             }
>         }
>
>         // exclude users
>         if(!empty($excludedusers)) {
>             foreach($excludedusers as $user) {
>                 if($change['user'] == $user) return false;
```

Once I had hacked syntax.php - first taking a backup, since this is not a very good way to make changes to a plugin - I placed the following on a wiki page:
```{{changes>type=create&render=pagelist(header,showdiff)&excludedusers=busy.editor}}```

This provided me with what I wanted: the 100 most recent changes by anyone other than the user busy.editor.

I regret that I am not in a position to submit this as a GitHub change, but hopefully this diff will be useful to someone.

**Comment by Benedictas** [comment]
Hi shallimus, thank you for your post. I just want to ask about signs you wrote, I am not sure what you mean with letters between row numbers. For example, what exactly means code "124a125,129"? Or, could you upload whole syntax.php file with changes?

Thanks, 
Bene

**Comment by shallimus** [comment]
[syntax.txt](https://github.com/cosmocode/changes/files/911485/syntax.txt)
You're welcome, @Benedictas.

"124a125,129" is diff output. . I found this [explanation of diff output on AskUbuntu](http://askubuntu.com/questions/56964/how-do-i-decipher-diff-output).

So in this case, at line 124 in the old file, some lines were added, which became lines 125-129 in the new file:
````124a125,129
>             case 'excludedusers':
>                 foreach(preg_split('/\s*,\s*/', $value) as $value) {
>                     $data[$name][] = $value;
>                 }
>                 break;
````

Not sure if you are more used to another kind of diff output, or if you are new to diff (a utility which shows the differences between two files).


Either way, you're right that it's better to provide the whole file. Please find it attached, with a .txt extension as GitHub won't accept it with a .php extension.

**Comment by FosseWay** [comment]
I've packaged the excludedusers functionality described in this Issue as PR #44 for consideration by @cosmocode.
