### ISSUE TITLE
An opposite of excludepages

### ISSUE THREAD

**Issue by karas1999** [cosmocode/changes#41]
Is there a way to only show some pages? 
I know there is a "excludepages" syntax. In fact I just need an opposite of this feature. 
My goal is to just show the change log of the page opened itself. Like:

`{{change>page=@PAGE@}}` 

It is useful if you want to export the whole page using dw2pdf and contain the change log in the pdf.

**Comment by annda** [comment]
This plugin does not have such a feature.
