### ISSUE TITLE
Can't install automatically

### ISSUE THREAD

**Issue by mlgarchery** [cosmocode/changes#45]
Hi,
for some reasons, I could not install the plugin automatically, i had to download it and install it manually via the upload.
I just wanted to report the problem.
Thank you

**Comment by Michaelsy** [comment]
Don't know whether this is the problem of @FirstWorldSlardar but my similar problem was: I couldn't find this plugin by the search of "changes" or "Changes". But I found it through "recent" and then I could install the plugin automatically.

**Comment by nurzu** [comment]
Thanks for the hint. This is very useful.

**Comment by Michaelsy** [comment]
> Changes not found when Searching.

Please more informations. Do you already tried the searchword "recent"? (As I wrote above.)

**Comment by fwolfst** [comment]
Still applies. In the "Search and Install Plugins" section in dokuwiki admin, searching for "Changes" "change" or "changed" will not result in this plugin being found.

**Comment by cjohnsonuk** [comment]
Changes still doesn't appear in the list.  If you search for the Author Andreas Gohr then Changes does appear in the list
