### ISSUE TITLE
Question about the difference between list and pagelist

### ISSUE THREAD

**Issue by diltigug** [cosmocode/changes#46]
Hello,
I have the following question:
The normal list view (render = list) also shows what has changed (eg deleted, created, or the heading where something was changed).
This information is not displayed in the table view (render = pagelist).
Is it possible to display this information in the table view?
If yes, how does it work?

**Comment by splitbrain** [comment]
please refer to https://www.dokuwiki.org/plugin:changes#output_renderer on how to pass flags to the used renderer and influence what is output.
