### ISSUE TITLE
Namespace Broken?

### ISSUE THREAD

**Issue by tracerrx** [cosmocode/changes#47]
Im trying to restrict to changes for a specific page only, but it looks like I can only restrict to it's parent namespace.  

NS1:NS2 works, but NS1:NS2:PAGE does not.

Is this the intended behavior?  Is there any way of restricting to that single page?

**Comment by annda** [comment]
As the [documentation](https://www.dokuwiki.org/plugin:changes) says, the plugin lists changes for the entire wiki or for a given namespace only.
