### ISSUE TITLE
More than the most recent change

### ISSUE THREAD

**Issue by bamboo122** [cosmocode/changes#53]
Is it possible to display more than just the one very recent change for a page? If I change something, the prevoius change disappears. I want to keep them all.
Thanks in advance!

**Comment by splitbrain** [comment]
Oh wait a minute. I thought this was on the main dokuwiki repo. Sorry. It's currently not possible in this plugin.

**Comment by bamboo122** [comment]
Thanks for the fast answer!

**Comment by jafeucht** [comment]
This is the issue I came here fore. Sometimes, I'd like to show that the same page has been modified more than once. If it is possible to revise this plugin to show multiple changes to the same page, that would make it much more useful and attractive to users in my opinion.

**Comment by jafeucht** [comment]
In fact, I'm right now looking for a similar plugin which can show multiple changes to the same page, because I would like users to see that multiple edits have been made to the same page.
