### ISSUE TITLE
What data source is used?

### ISSUE THREAD

**Issue by borgendorf** [cosmocode/changes#56]
Hi, I have a development wiki that I copy out to my production server for a release. I've noticed that the development wiki (where the edits were actually made) shows the list of recent changes, but when I copy the whole directory out to the production site, none of the changes are shown. Is there a file or folder perhaps that I'm missing in my copy so the recent change information can also be shown on the production wiki? Thanks!

**Comment by splitbrain** [comment]
This plugin uses the main dokuwiki changelog. The same you get when you open "Recent Changes".
