### ISSUE TITLE
Relative Namespace  for using in templates

### ISSUE THREAD

**Issue by roadrunnerjb** [cosmocode/changes#59]
Hi,
I have several templates and want to add a section for changes in subpages of this namespace.

I tried 

{{changes>ns=.}}   it displays the changes of the whole wiki 
or
{{changes>ns=@NS@}} displays nothing.

How can I achive this ?

Regards

**Comment by annda** [comment]
This is currently not possible, only literal namespaces are supported.

**Comment by cjohnsonuk** [comment]
@annda Is this technically not possible to code at all it or just the extension doesn't currently support it?  I'm wondering if its worth my time to fork the code to create a plugin tweaked to allow current name space searching

**Comment by annda** [comment]
@cjohnsonuk I think relative namespaces can be implemented relatively easily. It would be a bit more tricky when you want to include the syntax in other pages.

**Comment by cjohnsonuk** [comment]
@annda Thanks for confirming its possible.  I'll take a look, first at just relative, then if my brain has not frazzled on that I'll see whether it needs a lot more for using that in included sections.
@roadrunnerjb Now I know its possible I'll schedule some time but I'm in the middle of other projects at the moment. Once I've had a chance to see how relative namespaces are coded in other plugins I'll let you know when its ready for testing.

@annda if I can get it working would it be possible/would you be happy to merge this into the code of the main plugin?
