### ISSUE TITLE
Different output on different Wikis

### ISSUE THREAD

**Issue by chappy721** [cosmocode/changes#60]
Hello

I have a strange problem with no idea how to solve.
On two wikis (different servers, different hostings) I use the following syntax:
{{changes>5>render = pagelist}}

On one wiki only a list of pagenames appears
on the other wiki a kind of a table with pagenames, changedate and person who changed appears

On both wikis with the same syntax. Both have Greebo installed.

Any idea where to look for differences?

Thanks
Daniel

**Comment by splitbrain** [comment]
do you have the pagelist plugin installed in both wikis?
