### ISSUE TITLE
Embedding "Old revisions" into page as table list

### ISSUE THREAD

**Issue by spricer** [cosmocode/changes#63]
Is this plugins supposed to list changes of particular page itself or changes for particular sub-namespace that includes all pages within?
e.g.
{{changes>ns = bar:baz}}
I would like to embed in the page e.g. major changes list from "Old revisions".

**Comment by annda** [comment]
You seem to be already familiar with the [documentaion](https://www.dokuwiki.org/plugin:changes).

The plugin can indeed list **the most recent change** for every page in a given namespace, but it is not a replacement for the listing of revisions per page ("Old revisions" button).
