### ISSUE TITLE
Plugin Changes can not be found 

### ISSUE THREAD

**Issue by andreash1972** [cosmocode/changes#65]
Hi,
in my installation "Hogfather" (installed today 11.4.2022), the Plugin "Changes Plugin" can not be found by the Plugin-Search in the admin panel.

**Comment by McBart** [comment]
This is still the case in Igor

**Comment by GlitterHorn** [comment]
Same for Greebo :(

**Comment by gsileno** [comment]
Yep, still cannot be found. If I try to install it manually, it seems there is a checksum error. May this be the cause?

**Comment by rtzra** [comment]
Same for 2023-04-04a "Jack Jackrum"
Manual installation ok via download https://github.com/cosmocode/changes/zipball/master and "Manual installation"

**Comment by splitbrain** [comment]
duplicate of #45
