### ISSUE TITLE
Blank Page 

### ISSUE THREAD

**Issue by cmcastan** [cosmocode/changes#74]
### Issue Description

Hi

I create a page just with this code in Release 2020-07-29 "Hogfather":

{{changes>user = ccastan}}

When I save the page, nothing appears, i.e. a blank page appears, and it has also lost the side buttons for editing, changes etc...

![image](https://github.com/user-attachments/assets/8829e75f-4efe-49ba-95a5-d72aea18a477)

Regards and thanks in advance ;-)

**Comment by splitbrain** [comment]
https://www.dokuwiki.org/faq:blankpage

**Comment by splitbrain** [comment]
no further info provided
